[
	{
		question: "What is the primary cause of global warming?",
		correct_answer: "Greenhouse gas emissions",
		decoy_answers: [
			"Deforestation only",
			"Volcanic eruptions",
			"Tidal waves",
			"Solar flares",
		],
	},
	{
		question: "Which gas is most responsible for the greenhouse effect?",
		correct_answer: "Carbon dioxide",
		decoy_answers: ["Oxygen", "Nitrogen", "Helium", "Argon"],
	},
	{
		question: "What is the most effective way to reduce household waste?",
		correct_answer: "Reduce, reuse, recycle",
		decoy_answers: [
			"Burn trash in the backyard",
			"Throw everything in one bin",
			"Buy more plastic products",
			"Use disposable items",
		],
	},
	{
		question:
			"What is the process called when trees are removed faster than they can grow back?",
		correct_answer: "Deforestation",
		decoy_answers: [
			"Reforestation",
			"Urbanization",
			"Desertification",
			"Photosynthesis",
		],
	},
	{
		question: "Which renewable energy source is derived from the sun?",
		correct_answer: "Solar energy",
		decoy_answers: [
			"Geothermal energy",
			"Wind energy",
			"Hydropower",
			"Nuclear energy",
		],
	},
	{
		question: "What does 'biodegradable' mean?",
		correct_answer: "Can be broken down naturally by microorganisms",
		decoy_answers: [
			"Dissolves in water",
			"Melts at room temperature",
			"Lasts forever",
			"Is made from plastic",
		],
	},
	{
		question:
			"What type of pollution is caused by excessive artificial lighting?",
		correct_answer: "Light pollution",
		decoy_answers: [
			"Noise pollution",
			"Air pollution",
			"Water pollution",
			"Thermal pollution",
		],
	},
	{
		question: "Which of the following is a non-renewable resource?",
		correct_answer: "Coal",
		decoy_answers: [
			"Solar energy",
			"Wind energy",
			"Hydropower",
			"Geothermal energy",
		],
	},
	{
		question: "What is composting?",
		correct_answer: "A process of recycling organic waste into fertilizer",
		decoy_answers: [
			"Burning waste in a pit",
			"Mixing plastic and paper waste",
			"Dumping waste into rivers",
			"Melting metals for reuse",
		],
	},
	{
		question:
			"Which environmental agreement aims to limit global temperature rise?",
		correct_answer: "The Paris Agreement",
		decoy_answers: [
			"Kyoto Protocol",
			"Geneva Convention",
			"Montreal Protocol",
			"Stockholm Convention",
		],
	},
	{
		question: "Which layer of the atmosphere contains the ozone layer?",
		correct_answer: "Stratosphere",
		decoy_answers: ["Troposphere", "Mesosphere", "Thermosphere", "Exosphere"],
	},
	{
		question: "What is the main cause of ocean acidification?",
		correct_answer: "Absorption of CO₂ from the atmosphere",
		decoy_answers: [
			"Saltwater pollution",
			"Underwater volcanoes",
			"Oil spills",
			"Plastic waste",
		],
	},
	{
		question: "What is a carbon footprint?",
		correct_answer: "The total amount of greenhouse gases generated by actions",
		decoy_answers: [
			"Carbon left behind after burning wood",
			"Black marks from fossil fuels",
			"Air particles in a room",
			"A trace of soot on metal",
		],
	},
	{
		question: "Which is the most sustainable transportation option?",
		correct_answer: "Cycling",
		decoy_answers: [
			"Driving an SUV",
			"Riding a motorcycle",
			"Using a private jet",
			"Sailing a cruise ship",
		],
	},
	{
		question: "What is the main source of marine pollution?",
		correct_answer: "Plastic waste",
		decoy_answers: ["Algae", "Salt", "Whales", "Coral"],
	},
	{
		question: "Which practice helps conserve water?",
		correct_answer: "Fixing leaking taps",
		decoy_answers: [
			"Running sprinklers daily",
			"Washing cars frequently",
			"Using more water in toilets",
			"Boiling water longer",
		],
	},
	{
		question: "Which of the following is a greenhouse gas?",
		correct_answer: "Methane",
		decoy_answers: ["Ozone", "Hydrogen", "Chlorine", "Neon"],
	},
	{
		question: "Which ecosystem has the highest biodiversity?",
		correct_answer: "Tropical rainforest",
		decoy_answers: ["Desert", "Tundra", "Savannah", "Mountain"],
	},
	{
		question: "What is the major threat to polar bears?",
		correct_answer: "Melting sea ice",
		decoy_answers: ["Predators", "Volcanoes", "Earthquakes", "Food allergies"],
	},
	{
		question: "What is 'greenwashing'?",
		correct_answer:
			"Misleading marketing that suggests products are eco-friendly",
		decoy_answers: [
			"Washing clothes in cold water",
			"Using green paint on buildings",
			"Cleaning plants",
			"Recycling incorrectly",
		],
	},
	{
		question: "Which farming method is best for soil health?",
		correct_answer: "Crop rotation",
		decoy_answers: [
			"Monoculture",
			"Deforestation",
			"Overgrazing",
			"Tilling every day",
		],
	},
	{
		question: "Which of the following is a consequence of deforestation?",
		correct_answer: "Loss of biodiversity",
		decoy_answers: [
			"Increased rainfall",
			"Better air quality",
			"More food crops",
			"Faster tree growth",
		],
	},
	{
		question:
			"What is the most effective way to reduce air pollution from vehicles?",
		correct_answer: "Using public transportation",
		decoy_answers: [
			"Driving faster",
			"Using older cars",
			"Washing cars more often",
			"Filling gas tanks frequently",
		],
	},
	{
		question: "Which device can help save energy at home?",
		correct_answer: "Smart thermostat",
		decoy_answers: [
			"Electric heater",
			"Incandescent bulb",
			"Old refrigerator",
			"Gasoline generator",
		],
	},
	{
		question: "Which of the following is a sustainable fishing method?",
		correct_answer: "Line and pole fishing",
		decoy_answers: [
			"Bottom trawling",
			"Blast fishing",
			"Overfishing",
			"Drift netting",
		],
	},
	{
		question:
			"What is the term for species that are no longer found anywhere on Earth?",
		correct_answer: "Extinct",
		decoy_answers: ["Endangered", "Threatened", "Vulnerable", "Rare"],
	},
	{
		question: "Which renewable energy source uses wind to produce electricity?",
		correct_answer: "Wind turbines",
		decoy_answers: [
			"Solar panels",
			"Hydroelectric dams",
			"Fossil fuel plants",
			"Biogas digesters",
		],
	},
	{
		question:
			"Which environmental organization is known for its direct action?",
		correct_answer: "Greenpeace",
		decoy_answers: ["UNESCO", "WHO", "IMF", "World Bank"],
	},
	{
		question: "What is the main goal of environmental conservation?",
		correct_answer: "Protect natural resources for future generations",
		decoy_answers: [
			"Increase industrial output",
			"Build more cities",
			"Reduce wildlife",
			"Grow non-native plants",
		],
	},
	{
		question: "What household item is often improperly recycled?",
		correct_answer: "Plastic bags",
		decoy_answers: ["Glass bottles", "Aluminum cans", "Paper", "Cardboard"],
	},
];
